import { ExbaWidget } from '../../kernel/core/widget';
import { customElement, property } from '../../kernel/core/decorators';
import { t, ease } from '../../shell/styles';

/**
 * ExbaButton: A reusable button component with multiple variants.
 * Inspired by Flutter's Widget and Variant system.
 */
@customElement('exba-button')
export class ExbaButton extends ExbaWidget {
  @property('string') icon: string = '';
  @property('boolean') disabled: boolean = false;

  /** Base styles applied to all variants */
  static styles = {
    root: `
      display: inline-flex;
      align-items: center;
      justify-content: center;
      gap: 0.5rem;
      padding: 0.625rem 1.25rem;
      border-radius: 0.625rem;
      font-size: 0.875rem;
      font-weight: 500;
      cursor: pointer;
      transition: all ${ease};
      border: 1px solid transparent;
      user-select: none;
      font-family: inherit;
    `,
    icon: 'font-size: 1rem; opacity: 0.8;',
    disabled: 'opacity: 0.5; cursor: not-allowed; pointer-events: none;'
  };

  /** Design variants (Flutter-inspired) */
  static variants = {
    primary: {
      root: `background: ${t.indigo600}; color: ${t.white}; &:hover { background: ${t.indigo500}; transform: translateY(-1px); box-shadow: 0 4px 12px ${t.indigo600a}; }`
    },
    secondary: {
      root: `background: ${t.zinc800}; color: ${t.zinc100}; &:hover { background: ${t.zinc700}; }`
    },
    outline: {
      root: `background: transparent; border-color: ${t.zinc700}; color: ${t.zinc200}; &:hover { background: ${t.zinc800a}; border-color: ${t.zinc500}; }`
    },
    ghost: {
      root: `background: transparent; color: ${t.zinc400}; &:hover { background: ${t.zinc800a}; color: ${t.zinc100}; }`
    },
    danger: {
      root: `background: ${t.red600}; color: ${t.white}; &:hover { opacity: 0.9; }`
    }
  };

  /**
   * The build method focus on composition (UI structure).
   * @param classes The variant-aware class names generated by useStyles.
   */
  build(classes: Record<string, string>) {
    const disabledClass = this.disabled ? classes.disabled : '';
    
    return `
      <button class="${classes.root} ${disabledClass}" ?disabled="${this.disabled}">
        ${this.icon ? `<span class="${classes.icon}">${this.icon}</span>` : ''}
        <slot></slot>
      </button>
    `;
  }
}
